//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHuntData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVPostLog
    {
        public int CVPostId { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<System.DateTime> DateTakenDown { get; set; }
    }
}
