//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHuntData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobHuntEntities : DbContext
    {
        public JobHuntEntities()
            : base("name=JobHuntEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CVPostLog> CVPostLogs { get; set; }
        public DbSet<WhereFound> WhereFounds { get; set; }
        public DbSet<WhoFound> WhoFounds { get; set; }
        public DbSet<JobType> JobTypes { get; set; }
        public DbSet<JobHuntLog> JobHuntLogs { get; set; }
    }
}
